name: pester

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser
          Invoke-Pester -Path ./tests -CI
